# Snakefile
configfile: "config/config.yml"
home= config["home_dir"]
sample= "Sample001"
rule all:
    input:
        parse_ph = expand(f'{home}/output/metaphlan/{sample}_phylum.csv',home= home, sample=sample),
        parse_sp = expand(f'{home}/output/metaphlan/{sample}_species.csv',home= home, sample=sample),
        pie_plot = expand(f"{home}/output/metaphlan/{sample}_phylum.png",home= home, sample=sample),
        count_file= expand(f"{home}/output/metaphlan/{sample}_count.csv",home= home, sample=sample),
        ratio_plot = expand(f"{home}/output/metaphlan/{sample}_phylum_ratio.png",home= home, sample=sample),
        fb = expand(f"{home}/output/metaphlan/{sample}_fb.csv",home= home, sample=sample),
        top15_plot = expand(f"{home}/output/metaphlan/{sample}_species_top15.png",home= home, sample=sample),
        metrics= expand(f"{home}/output/metaphlan/{sample}_metrics.csv",home= home, sample=sample),
        richness= expand(f"{home}/output/metaphlan/{sample}_gauge_richness.png",home= home, sample=sample),
        shannon= expand(f"{home}/output/metaphlan/{sample}_gauge_shannon.png",home= home, sample=sample),
        evenness= expand(f"{home}/output/metaphlan/{sample}_gauge_evenness.png",home= home, sample=sample),
        beneficial= expand(f"{home}/output/metaphlan/{sample}_beneficial_sp.csv",home= home, sample=sample),
        gmwi2_score = expand(f"{home}/output/metaphlan/{sample}_gmwi2_score.txt",home= home, sample=sample),
        gmwi2_taxa = expand(f"{home}/output/metaphlan/{sample}_gmwi2_taxa.txt",home= home, sample=sample),
        gmwi2_plot = expand(f"{home}/output/metaphlan/{sample}_gmwi2_plot.png",home= home, sample=sample),
        gmwi2_csv = expand(f"{home}/output/metaphlan/{sample}_gmwi2.csv",home= home, sample=sample),
        metadata = expand(f"{home}/output/metaphlan/{sample}_metadata.csv",home= home, sample=sample),
        pdf = expand(f"{home}/output/metaphlan/{sample}_Gut_microbiome.pdf",home= home, sample=sample)
    
rule install_r_packages:
    input:
        f"{home}/scripts/install_packages.R"
    output:
        "logs/r_packages_installed.log"
    conda:
        f"{home}/envs/r_env.yml"
    shell:
        """
        Rscript {input}
        echo "R packages installed" > {output}
        """

rule parse_metaphlan:
    input:
        metaphlan = f"{home}/input/metaphlan/{sample}_profiled_mpa4.txt"
    output:
        phylum = f"{home}/output/metaphlan/{sample}_phylum.csv",
        species = f"{home}/output/metaphlan/{sample}_species.csv",
        count_file = f"{home}/output/metaphlan/{sample}_count.csv"
    script:
        f"{home}/scripts/parse_metaphlan.py"

rule plot_phylum_pie:
    input:
        table = f"{home}/output/metaphlan/{sample}_phylum.csv"
    output:
        plot = f"{home}/output/metaphlan/{sample}_phylum.png"
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/plot_phylum_piechart.R"
    shell:
        "Rscript {params.script} {input.table} {output.plot}"

rule plot_phylum_ratio:
    input:
        table = f"{home}/output/metaphlan/{sample}_phylum.csv"
    output:
        plot = f"{home}/output/metaphlan/{sample}_phylum_ratio.png",
        fb= f"{home}/output/metaphlan/{sample}_fb.csv"
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/plot_phylum_ratio.R"
    shell:
        "Rscript {params.script} {input.table} {output.plot} {output.fb}"

rule plot_species_top15:
    input:
        table = f"{home}/output/metaphlan/{sample}_species.csv"
    output:
        plot = f"{home}/output/metaphlan/{sample}_species_top15.png",
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/top15_2.R",
    shell:
        """
        Rscript {params.script} {input.table} {output.plot}
        """

rule calculate_metrics:
    input:
        csv= f"{home}/output/metaphlan/{sample}_species.csv",
    output:
        csv= f"{home}/output/metaphlan/{sample}_metrics.csv",
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/calculate_metrics.R",
    shell:
        """
        Rscript {params.script} {input.csv} {output.csv}
        """

rule gauge_richness:
    input:
        csv = f"{home}/output/metaphlan/{sample}_metrics.csv",
    output:
        plot = f"{home}/output/metaphlan/{sample}_gauge_richness.png",
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/gauge_richness.R",
    shell:
        """
        Rscript {params.script} {input.csv} {output.plot}
        """

rule gauge_shannon:
    input:
        csv = f"{home}/output/metaphlan/{sample}_metrics.csv",
    output:
        plot = f"{home}/output/metaphlan/{sample}_gauge_shannon.png",
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/gauge_shannon.R",
    shell:
        """
        Rscript {params.script} {input.csv} {output.plot}
        """

rule gauge_evenness:
    input:
        csv = f"{home}/output/metaphlan/{sample}_metrics.csv",
    output:
        plot = f"{home}/output/metaphlan/{sample}_gauge_evenness.png",
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/gauge_evenness.R",
    shell:
        """
        Rscript {params.script} {input.csv} {output.plot}
        """

rule beneficial_table:
    input:
        top20 = f"{home}/input/metaphlan/New_Top20.xlsx",
        updated = f"{home}/input/metaphlan/New_List_of_Organisms_Updated.xlsx",
        csv= f"{home}/output/metaphlan/{sample}_species.csv",
    output:
        csv = f"{home}/output/metaphlan/{sample}_beneficial_sp.csv",
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/beneficial_sp.R",
    shell:
        """
        Rscript {params.script} {input.top20} {input.updated} {input.csv} {output.csv}
        """
rule gmwi2_score:
    input:
        mpa3 = f"{home}/input/metaphlan/{sample}_metaphlan.txt"
    output:
        score = f"{home}/output/metaphlan/{sample}_gmwi2_score.txt",
        taxa = f"{home}/output/metaphlan/{sample}_gmwi2_taxa.txt",
    conda:
        f"{home}/envs/gmwi2_env.yml"
    params:
        script =f"{home}/GMWI2/src/GMWI2/my.py"
    shell:
        """
        python -m pip show joblib || python -m pip install joblib
        python -m pip show halo || python -m pip install halo
        python -m pip show scikit-learn || python -m pip install scikit-learn
        python {params.script} {input.mpa3} {output.score} {output.taxa}
        """
rule gmwi2_plot:
    input:
        score = f"{home}/output/metaphlan/{sample}_gmwi2_score.txt",
    output:
        plot = f"{home}/output/metaphlan/{sample}_gmwi2_plot.png",
        csv= f"{home}/output/metaphlan/{sample}_gmwi2.csv"
    conda:
        f"{home}/envs/r_env.yml"
    params:
        script= f"{home}/scripts/gmwi2_plot.R",
    shell:
        """
        Rscript {params.script} {input.score} {output.plot} {output.csv}
        """
rule merge_metadata:
    input:
        metrics= f"{home}/output/metaphlan/{sample}_metrics.csv",
        fb= f"{home}/output/metaphlan/{sample}_fb.csv",
        gmwi2 = f"{home}/output/metaphlan/{sample}_gmwi2.csv",
        count_file = f"{home}/output/metaphlan/{sample}_count.csv"
    output:
        csv= f"{home}/output/metaphlan/{sample}_metadata.csv"
    params:
        script= f"{home}/scripts/merge.py",
    shell:
        """
        python {params.script} {input.metrics} {input.fb} {input.gmwi2} {input.count_file} {output.csv}
        """
rule pdf_generation:
    input:
        meta= f"{home}/output/metaphlan/{sample}_metadata.csv"
    output:
        pdf = f"{home}/output/metaphlan/{sample}_Gut_microbiome.pdf"
    params:
        script= f"{home}/scripts/HPc_Python_copy.py",
        home_dir = f"{home}"
    shell:
        """
        pip install reportlab
        python {params.script} {input.meta} {output.pdf} {params.home_dir}
        """